version: "3.9"
services:
    web:
        build:
            context: .
            dockerfile: ./SunsetSunriseApi/Dockerfile
        ports:
            - "8000:80"
            - "8001:443"
        depends_on:
            - db
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "WeatherApi9!"
            ACCEPT_EULA: "Y"
        ports:
          - 1443:1433
        volumes:
          - ./SunsetSunriseApi/Backup:/var/lib/mssql/backup